# Personal info
name: Kunlin Han
email: hi@iwktd.com
phone: 123-456-7890
website: https://www.iwktd.com/

order:
  - Education
  - Skills
  - Experience
  - Projects
  - Leadership and Involvement

content:
  - title: Education
    layout: list
    content:
      - title: University of Southern California (USC)
        location: Los Angeles, CA
        sub_title: |
          Master of Electrical Engineering; GPA: 4.0/4.0
        duration: Dec. 2021-Dec. 2023
      - title: South China Normal University (SCNU)
        location: Guangzhou, China
        sub_title: |
          Bachelor of Network Engineering; GPA: 3.78/4.0; Rank: 1/72
        duration: Sept. 2017-Jun. 2021

  - title: Experience
    layout: list
    content:
      - title: CS Department, USC
        location: Los Angeles, CA
        sub_title: Graduate Teaching Assistant
        duration: May 2022-Aug. 2022
        link: https://bytes.usc.edu/cs455saty/m22_Coding-Rocks/home/index.html
        description: 
          - Coordinated with Prof. Saty Raghavachary as teaching assistant (course producer) in CSCI-455X Introduction to Programming Systems Design.
          - Presented labs to help students to understand the usage and importance of debugging (GDB) and get an overview of Computer Systems.
          - Held weekly office hours to help students with problems in assignments and labs.
      - show: false
        title: Lab 131, School of Computer Science, SCNU
        location: Los Angeles, CA
        sub_title: Instructor
        duration: Sept. 2018-Jun. 2021
        description: 
          - Recruited and manage members for the Lab. 
          - "Organized and instructed members to study CS topics: Algorithm (CLRS), Linear Algebra (GSLA), Computer System (CSAPP), Computation Theory (ITOC) and Functional Programming (SICP). "

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - title: Design and Implementation of 5-stage Pipeline Processor
        location: Sept. 2022-Oct. 2022
        description: 
          - Described Data Path Unit and Control Unit for single-cycle CPU with basic MIPS instructions.
          - Resolved problems related to Data Dependency and Early Branching.
          - Utilized RTL in Verilog and build 5-stage (IF, ID, EX, ME, WB) pipeline with encoded control signal, Internal Forwarding Register File and Early Branching.
      - title: Full-Custom Design Layout of Arbiter System with Multiplier and Divider
        description: 
          - Designed, implemented and drew layout of a ALU supporting 5-bit multiplication and 10-bit division and a 2-1 Round-Robin-based Arbiter with multiply and divide request with the Cadence Virtuoso and GPDK 45nm.
          - Planned, routed and simulated all aforementioned components with Cadence Virtuoso and Spectre and checked DRC and LVS with Mentor Graphics Calibre. 

  - title: Leadership and Involvement
    layout: list
    content: 
      - title: Hope Center, Reality L.A.
        location: Los Angeles, CA
        sub_title: Volunteer
        duration: Mar. 2022-Aug. 2022
        description: 
          - Sorted, organized and shelved food donations for storage to preserve food and accelerate cooking.
          - Managed and distributed cooked food with other volunteers.
          - Coordinated and helped out in cleaning utensils after food distribution. 
      - title: Network Club, SCNU
        location: Guangzhou, China
        sub_title: Vice President of Technical Department
        duration: Sept. 2017-Jun. 2019
        description: 
          - Managed existing members and held interviews to recruit members for Technical department.
          - Provided technical supports to on-campus IT activities, including development and maintenance of school forum, holding CTF competition.
          - Organized members to write articles about popular computer-related topics, such as resolution of DNS, anti-phishing, and published them in social media to enrich students' knowledge. 

  - title: Skills
    layout: text
    content: 
      - Programming Languages: Python, C/C++, Verilog, SystemVerilog, Java, Rust, SQL, x86 ASM
      - Libraries: Scrapy, BeautifulSoup, Requests, Django, Flutter
      - Cadence Tools: Virtuoso, Spectre, Xcelium
      - Mentor Graphics Tools: ModelSim, QuestaSim, Calibre
      - Tools: UNIX, Makefile, Xilinx Vivado, Intel Quartus, Git, Docker, PostGIS, ArcGIS
